name: Go

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.23

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

  benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "stable"

      - name: Run benchmark on PR or Main
        run: |
          mkdir -p cache
          go test -bench . -benchmem -run=^$ ./... > output.txt

      - name: Cache previous benchmark results
        if: github.ref == 'refs/heads/main'
        uses: actions/cache@v4
        with:
          path: ./cache
          key: ${{ runner.os }}-main-benchmarks

      - name: Store benchmark result
        run: |
          # Make sure to copy the benchmark output into the expected JSON format
          # This requires transforming the output.txt into benchmark-data.json
          # For example, use tools like `benchstat` or `go-benchmark-compare`
          mv output.txt cache/benchmark-data.json
        continue-on-error: true

      - name: Upload benchmark data
        uses: rhysd/github-action-benchmark@v1
        with:
          tool: "go"
          output-file-path: output.txt
          external-data-json-path: ./cache/benchmark-data.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          comment-on-alert: true
          fail-on-alert: true
