name: Go

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  pull-requests: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: "stable"

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

  benchmark:
    name: Run Go benchmark example
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v4
        with:
          go-version: "stable"

      - name: Run benchmark
        run: |
          mkdir -p cache
          go test -bench . -benchmem -run=^$ ./... | tee output.txt

      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: Go Benchmark
          tool: "go"
          output-file-path: output.txt
          github-token: ${{ secrets.GITHUB_TOKEN }}
          alert-threshold: "200%"
          comment-on-alert: true
          fail-on-alert: true
          summary-always: true
          alert-comment-cc-users: "@Masorubka"
